# Question:1
Convert a 1D array to a 2D array with 2 rows?
Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.reshape((2,5), order='F')

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

# Question:2
How to stack two arrays vertically?
Desired Output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [23]:
arr1=np.arange(0,10)

In [24]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr1=arr1.reshape((2,5), order='F')

In [26]:
arr1

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [30]:
arr2=np.ones(10)

In [28]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
arr2=arr2.astype('int32')

In [33]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
arr2=arr2.reshape((2,5), order='F')

In [35]:
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.concatenate((arr1,arr2), axis=0)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3
How to stack two arrays horizontally?
Desired Output::
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])