In [1]:
import numpy as np

In [2]:
x=[[1,3,5],[7,9,0]]

In [3]:
arr1=np.array(x)

In [4]:
arr1

array([[1, 3, 5],
       [7, 9, 0]])

In [5]:
y=[[11,13,15],[17,19,10]]

In [6]:
arr2=np.array(y)

In [7]:
arr2

array([[11, 13, 15],
       [17, 19, 10]])

In [8]:
#making two lists x and y and then converting them into the numpy arrays  arr1 and arr2, now we will tray to concatenate them

In [9]:
#first we will concatenate it and the axis we will specify as '0'

In [11]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [12]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [13]:
#similarly we can do this type of concatenation using the hstack and vstack without specifying the axis such as:

In [14]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [15]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])