In [1]:
import numpy as np

In [2]:
x=np.array([10,9,8,6,11])

In [3]:
x

array([10,  9,  8,  6, 11])

In [4]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [5]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [8]:
np.power(x,10)

array([1410065408, -808182895, 1073741824,   60466176,  167620825],
      dtype=int32)

In [9]:
y=[7,1,2,3,-1]

In [10]:
y


[7, 1, 2, 3, -1]

In [11]:
np.maximum(x,y)

array([10,  9,  8,  6, 11])