In [1]:
import numpy as np

In [2]:
x=np.array([10,9,7,10,7])

In [3]:
#For checking the average of all the elements of array we use the mean() function such as

In [4]:
x.mean()

8.6

In [5]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [6]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [7]:
y=x>6

In [8]:
y

array([ True,  True,  True,  True,  True])

In [9]:
y.sum()

5

In [10]:
y.any()

True

In [11]:
y.all()

True

In [12]:
x.sort()

In [13]:
x

array([ 7,  7,  9, 10, 10])

In [15]:
np.unique(x)

array([ 7,  9, 10])