In [1]:
import numpy as np

In [2]:
x=np.zeros((4,4))

In [3]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
l=[1,4,5,7]

In [5]:
np.array(l)

array([1, 4, 5, 7])

In [6]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
x=np.arange(1,100,10)

In [8]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
x.shape

(10,)

In [10]:
x=np.shape((10,10))

In [11]:
x.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [12]:
x=np.zeros((10,10))

In [13]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
y=x.reshape((2,2,5,5))

In [15]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
x.shape

(10, 10)

In [17]:
y.shape

(2, 2, 5, 5)

In [18]:
y.dtype

dtype('float64')

In [19]:
x.dtype

dtype('float64')

In [20]:
y.ndim


4

In [21]:
x.ndim

2

In [22]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [23]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [27]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
2/arr

array([[2.        , 1.        , 0.66666667],
       [0.5       , 0.4       , 0.33333333]])

In [31]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [34]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [35]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [36]:
arrtype=arr2>arr

In [37]:
arrtype

array([[False,  True, False],
       [ True, False,  True]])

In [38]:
arrtype.dtype

dtype('bool')

In [39]:
import numpy as np


In [41]:
a=np.random.randn((10))

In [42]:
b=np.random.randn((10))

In [43]:
b


array([ 0.02060324, -0.82845951, -0.42009461,  0.93004082,  0.48776755,
        1.13436347, -2.74002438,  0.92831493, -1.71063378,  0.71513492])

In [44]:
a+b

array([ 0.4523804 , -1.91112543,  1.55826733,  1.41359316, -0.19591484,
        1.20778694, -2.83161897, -0.76671525, -2.45097107,  0.54187991])

In [45]:
2*a

array([ 0.86355434, -2.16533185,  3.95672388,  0.96710468, -1.36736477,
        0.14684693, -0.18318918, -3.39006036, -1.48067458, -0.34651003])

In [46]:
1/a

array([  2.31600945,  -0.92364595,   0.50546868,   2.06802846,
        -1.46266749,  13.61962441, -10.91767555,  -0.58996   ,
        -1.35073569,  -5.77183878])

In [47]:
a>0

array([ True, False,  True,  True, False,  True, False, False, False,
       False])

In [48]:
a[a>0]

array([0.43177717, 1.97836194, 0.48355234, 0.07342346])