In [1]:
import numpy as np

In [4]:
#suppose we create a random array of 4x5 size said 'x'

In [5]:
x=np.random.randn(4,5)

In [6]:
x

array([[ 1.66834275,  0.91582286,  0.75986671, -0.91092229, -0.49764343],
       [-1.7351259 , -0.33650298,  0.00300185,  0.09278185, -0.06655524],
       [ 0.00621455,  1.43662751, -0.08767418,  1.11128395, -0.59776924],
       [-0.65853313,  0.86349355, -1.70967334,  0.67491392, -1.67728753]])

In [7]:
x.reshape(2,2,5)

array([[[ 1.66834275,  0.91582286,  0.75986671, -0.91092229,
         -0.49764343],
        [-1.7351259 , -0.33650298,  0.00300185,  0.09278185,
         -0.06655524]],

       [[ 0.00621455,  1.43662751, -0.08767418,  1.11128395,
         -0.59776924],
        [-0.65853313,  0.86349355, -1.70967334,  0.67491392,
         -1.67728753]]])

In [9]:
x.reshape((2,2,5),order='F')

array([[[ 1.66834275,  0.91582286,  0.75986671, -0.91092229,
         -0.49764343],
        [ 0.00621455,  1.43662751, -0.08767418,  1.11128395,
         -0.59776924]],

       [[-1.7351259 , -0.33650298,  0.00300185,  0.09278185,
         -0.06655524],
        [-0.65853313,  0.86349355, -1.70967334,  0.67491392,
         -1.67728753]]])

In [10]:
#skipping one specific dimension by giving -1

In [11]:
x.reshape(2,2,-1)

array([[[ 1.66834275,  0.91582286,  0.75986671, -0.91092229,
         -0.49764343],
        [-1.7351259 , -0.33650298,  0.00300185,  0.09278185,
         -0.06655524]],

       [[ 0.00621455,  1.43662751, -0.08767418,  1.11128395,
         -0.59776924],
        [-0.65853313,  0.86349355, -1.70967334,  0.67491392,
         -1.67728753]]])

In [12]:
x.ravel()

array([ 1.66834275,  0.91582286,  0.75986671, -0.91092229, -0.49764343,
       -1.7351259 , -0.33650298,  0.00300185,  0.09278185, -0.06655524,
        0.00621455,  1.43662751, -0.08767418,  1.11128395, -0.59776924,
       -0.65853313,  0.86349355, -1.70967334,  0.67491392, -1.67728753])

In [13]:
x.flatten()

array([ 1.66834275,  0.91582286,  0.75986671, -0.91092229, -0.49764343,
       -1.7351259 , -0.33650298,  0.00300185,  0.09278185, -0.06655524,
        0.00621455,  1.43662751, -0.08767418,  1.11128395, -0.59776924,
       -0.65853313,  0.86349355, -1.70967334,  0.67491392, -1.67728753])