In [1]:
import numpy as np

In [2]:
x=[1,4,5,6,7,9,1,4]

In [3]:
x

[1, 4, 5, 6, 7, 9, 1, 4]

In [4]:
d=np.array(x)

In [5]:
d

array([1, 4, 5, 6, 7, 9, 1, 4])

In [8]:
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [9]:
#if i would have 2 dimensional array then 

In [10]:
x=[[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]]

In [11]:
x

[[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [13]:
c=np.array(x)

In [14]:
c

array([[ 1,  4,  5,  6,  7,  9,  1,  4],
       [11, 14, 15, 16, 17, 19, 11, 14]])

In [16]:
np.split(c,[2,5],axis=1)

[array([[ 1,  4],
        [11, 14]]),
 array([[ 5,  6,  7],
        [15, 16, 17]]),
 array([[ 9,  1,  4],
        [19, 11, 14]])]

In [17]:
#splitting column wise in the case of 2 dimensional arrays

In [18]:
#now we will split the 2 dimensional arrays as rows wise

In [19]:
np.split(c,[1],axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]